name: Pylint Check

on:
  push:
    branches:
      - "**" # Se ejecuta en todas las ramas
  pull_request:
    branches:
      - "**" # Se ejecuta en pull requests desde todas las ramas

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r ./FastApi/requirements.txt  # Instala todas las dependencias listadas en requirements.txt

      - name: Run Pylint and capture score
        id: pylint
        run: |
          score=$(pylint ./**/*.py --fail-under=0 --output-format=text | grep "Your code has been rated at" | awk '{print $7}' | cut -d/ -f1)
          echo "Pylint score is $score"
          echo "::set-output name=score::$score"

      - name: Check Pylint Score
        run: |
          if (( $(echo "${{ steps.pylint.outputs.score }} > 7" | bc -l) )); then
            echo "Pylint score is greater than 7, proceeding."
          else
            echo "Pylint score is not greater than 7. Failing the build."
            exit 1
